# Generated by Django 3.2.6 on 2022-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_distributor_distributorkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
