# Generated by Django 3.2.6 on 2022-01-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_remote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='distributor_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=1024)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.distributor')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.key')),
            ],
            options={
                'unique_together': {('distributor', 'key')},
            },
        ),
    ]
