# Generated by Django 3.2.6 on 2021-08-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_vehicleapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='application',
        ),
    ]
