# Generated by Django 3.2.6 on 2021-11-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_remove_key_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('key_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lookup.key')),
                ('sku', models.CharField(max_length=255)),
                ('fcc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('lookup.key',),
        ),
    ]
