# Generated by Django 3.2.6 on 2021-12-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DistributorKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.distributor')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.key')),
            ],
            options={
                'unique_together': {('distributor', 'key')},
            },
        ),
    ]
