# Generated by Django 3.2.6 on 2021-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_auto_20211216_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorkey',
            name='link',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
