# Generated by Django 3.2.6 on 2021-12-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_distributor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='distributor_logos/'),
        ),
    ]
