# Generated by Django 3.2.7 on 2022-10-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_distributor_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('remote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lookup.remote')),
            ],
        ),
        migrations.CreateModel(
            name='KeyShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lookup.key')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('remote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lookup.remote')),
            ],
        ),
        migrations.AddField(
            model_name='vehicleapplication',
            name='emergency_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.emergencykey'),
        ),
        migrations.AddField(
            model_name='vehicleapplication',
            name='key_shell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.keyshell'),
        ),
        migrations.AddField(
            model_name='vehicleapplication',
            name='remote_shell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.remoteshell'),
        ),
    ]
