# Generated by Django 3.2.7 on 2023-01-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0011_auto_20221009_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransponderKey',
            fields=[
                ('key_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lookup.key')),
                ('sku', models.CharField(max_length=255)),
            ],
            bases=('lookup.key',),
        ),
    ]
