# Generated by Django 5.1.2 on 2025-04-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0014_distributor_created_at_distributor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='logo_height',
            field=models.IntegerField(default=75),
        ),
    ]
